/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    // By default, Docusaurus generates a sidebar from the docs folder structure
    // tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],


    // But you can create a sidebar manually

    tutorialSidebar: [
        {
            type: 'autogenerated',
            dirName: 'introduccion',
        },
        {
            type: 'link',
            label: 'Normas académicas y administrativas',
            href: 'http://sistemas-utnfra.com.ar/Reglamento.pdf'
        },
    ],
    Clases: [
        "clases/programa",
        "clases/referencias",
        {
            type: 'category',
            label: 'Introducción a .NET y C#',
            collapsible: true,
            collapsed: true,
            items:
                [
                    {
                        type: 'autogenerated',
                        dirName: 'clases/01-introduccion',
                    }
                ]
        },
        {
            type: 'category',
            label: 'Métodos estáticos',
            collapsible: true,
            collapsed: true,
            items:
                [
                    {
                        type: 'autogenerated',
                        dirName: 'clases/02-estaticos',
                    }
                ]
        },
    ],
};

module.exports = sidebars;
